import prisma from "../utils/prisma.js";
import express from "express";
import multer from "multer";
import multerS3 from "multer-s3";
import { S3Client } from "@aws-sdk/client-s3";
import { notifyUser } from "../services/notificationService.js";
import logger from "../utils/logger.js";
import nodemailer from "nodemailer";
import redis from "../utils/redis.js";

const router = express.Router();

// AWS S3 CONFIGURATION
const s3 = new S3Client({
  region: process.env.AWS_REGION || "us-east-2",
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
  },
});

const upload = multer({
  storage: multerS3({
    s3: s3,
    bucket: process.env.AWS_S3_BUCKET!,
    metadata: function (req, file, cb) {
      cb(null, { fieldName: file.fieldname });
    },
    key: function (req, file, cb) {
      const uniqueSuffix = Date.now() + "-" + Math.round(Math.random() * 1e9);
      // Stores files securely in a "workorders" folder inside your S3 bucket
      cb(null, `workorders/${uniqueSuffix}-${file.originalname}`); 
    },
  }),
});

// EMAIL TRANSPORTER CONFIGURATION
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

// Helper Functions
const calculateNextDate = (currentDate: Date, scheduleType: string): Date => {
  const nextDate = new Date(currentDate);
  if (scheduleType === "DAILY") nextDate.setDate(nextDate.getDate() + 1);
  if (scheduleType === "WEEKLY") nextDate.setDate(nextDate.getDate() + 7);
  if (scheduleType === "MONTHLY") nextDate.setMonth(nextDate.getMonth() + 1);
  if (scheduleType === "QUARTERLY") nextDate.setMonth(nextDate.getMonth() + 3);
  if (scheduleType === "YEARLY") nextDate.setFullYear(nextDate.getFullYear() + 1);
  return nextDate;
};

// 1. Upload Document to AWS S3
router.post("/:id/documents", upload.single("file"), async (req: any, res: any) => {
  try {
    if (!req.file) return res.status(400).json({ error: "No file uploaded" });

    const numericId = parseInt(req.params.id);
    const fileUrl = req.file.location; // This is the public S3 URL generated by multer-s3

    const document = await prisma.document.create({
      data: {
        fileName: req.file.originalname,
        fileUrl: fileUrl, 
        workOrderId: numericId,
        uploaderId: req.body.uploaderId,
      },
    });

    const wo = await prisma.workOrder.findUnique({ where: { id: numericId }, select: { organizationId: true, title: true }});

    if (wo) {
      await redis.del(`workorders:${wo.organizationId}`).catch(() => {});
      await redis.del(`workorder:single:${numericId}`).catch(() => {});
      
      // LOG ACTIVITY TO UNIVERSAL STREAM
      await prisma.activityLog.create({
        data: {
          action: `uploaded a file: ${req.file.originalname}`,
          entityType: "WORK_ORDER",
          entityTitle: `WO-${numericId}`,
          workOrderId: numericId,
          actorId: req.body.uploaderId,
          organizationId: wo.organizationId,
        }
      });
    }

    res.status(201).json(document);
  } catch (error) {
    logger.error(`[WorkOrders] Upload Document Error: ${(error as Error).message || error}`);
    res.status(500).json({ error: "Failed to upload document" });
  }
});

// 2. Get All Work Orders
router.get("/", async (req, res) => {
  try {
    const {
      orgId,
      page = "1",
      limit = "50",
      search = "",
      status,
      category,
      locationName,
      teamId,
    } = req.query;

    if (!orgId) return res.status(400).json({ error: "Organization ID is required" });

    const cacheKey = `workorders:${orgId}:${page}:${limit}:${search}:${status || "ALL"}:${category || "ALL"}:${locationName || "ALL"}:${teamId || "ALL"}`;

    let cachedData = null;
    try {
      const data = await redis.get(cacheKey);
      if (data) cachedData = JSON.parse(data);
    } catch (redisErr) {}

    if (cachedData) {
      return res.json(cachedData);
    }

    const queryConditions: any = { organizationId: String(orgId) };

    if (status && status !== "ALL") queryConditions.status = status;
    if (category && category !== "ALL") queryConditions.category = category;

    if (locationName && locationName !== "ALL") {
      queryConditions.locationName = { contains: String(locationName), mode: "insensitive" };
    }

    if (teamId && teamId !== "ALL") queryConditions.teamId = teamId;

    if (search && typeof search === "string" && search.trim() !== "") {
      const searchNum = parseInt(search.replace(/\D/g, ""));

      queryConditions.OR = [
        { title: { contains: search.trim(), mode: "insensitive" } },
        ...(isNaN(searchNum) ? [] : [{ id: searchNum }]),
      ];
    }

    const pageNumber = parseInt(page as string, 10);
    const limitNumber = parseInt(limit as string, 10);
    const skip = (pageNumber - 1) * limitNumber;

    const [totalRecords, workOrders] = await Promise.all([
      prisma.workOrder.count({ where: queryConditions }),
      prisma.workOrder.findMany({
        where: queryConditions,
        skip: skip,
        take: limitNumber,
        orderBy: { id: "desc" },
        include: { assignee: true, team: true, asset: true },
      }),
    ]);

    const responsePayload = {
      data: workOrders,
      meta: {
        totalRecords,
        totalPages: Math.ceil(totalRecords / limitNumber),
        currentPage: pageNumber,
        limit: limitNumber,
      },
    };

    await redis.setex(cacheKey, 60, JSON.stringify(responsePayload)).catch(() => {});

    res.json(responsePayload);
  } catch (error: any) {
    logger.error(`[WorkOrders] Fetch All Error: ${error.message || error}`);
    res.status(500).json({ error: "Failed to fetch work orders" });
  }
});

// 3. Get Single Work Order
router.get("/:id", async (req, res) => {
  const { id } = req.params;
  try {
    const numericId = parseInt(id);
    if (isNaN(numericId)) return res.status(400).json({ error: "Invalid ID format" });

    const cacheKey = `workorder:single:${numericId}`;
    let cachedWorkOrder = null;
    try {
      const data = await redis.get(cacheKey);
      if (data) cachedWorkOrder = JSON.parse(data);
    } catch (e) {}

    if (cachedWorkOrder) return res.status(200).json(cachedWorkOrder);

    const workOrder = await prisma.workOrder.findUnique({
      where: { id: numericId },
      include: {
        assignee: true,
        creator: true,
        asset: true,
        team: true,
        comments: { include: { author: true }, orderBy: { createdAt: "asc" } },
        activityLogs: { include: { actor: true }, orderBy: { createdAt: "asc" } },
        preventiveMaintenance: true,
        documents: { include: { uploader: true } },
      },
    });

    if (!workOrder) return res.status(404).json({ error: "Work order not found" });

    await redis.setex(cacheKey, 60, JSON.stringify(workOrder)).catch(() => {});
    res.status(200).json(workOrder);
  } catch (error) {
    logger.error(`[WorkOrders] Fetch Single Error: ${(error as Error).message || error}`);
    res.status(500).json({ error: "Failed to fetch work order details" });
  }
});

// 4. Create Work Order
router.post("/", async (req, res) => {
  const {
    title,
    description,
    category,
    priority,
    organizationId,
    createdBy,
    assignedTo,
    additionalAssigneeEmails,
    teamId,
    assetId,
    dueDate,
    durationHours,
    estimatedHours,
    locationName,
    parentWorkOrderId,
  } = req.body;

  try {
    let parsedHours = null;
    if (durationHours && !isNaN(parseFloat(durationHours))) parsedHours = parseFloat(durationHours);
    else if (estimatedHours && !isNaN(parseFloat(estimatedHours)))
      parsedHours = parseFloat(estimatedHours);

    let resolvedLocationName = locationName || null;
    if (resolvedLocationName && organizationId) {
      try {
        const allLocations = await prisma.location.findMany({
          where: { organizationId: String(organizationId) },
        });
        const matchedLoc = allLocations.find(
          (l) =>
            l.name.toLowerCase() === resolvedLocationName.toLowerCase() ||
            l.name.toLowerCase().includes(resolvedLocationName.toLowerCase()) ||
            (l.shortName && l.shortName.toLowerCase() === resolvedLocationName.toLowerCase())
        );
        if (matchedLoc) {
          resolvedLocationName = matchedLoc.name;
        }
      } catch (locErr) {
        logger.warn(`Could not resolve location name: ${(locErr as Error).message}`);
      }
    }

    let finalAssignee = assignedTo || null;
    let finalAdditionalEmails = additionalAssigneeEmails || null;
    let finalTeam = teamId || null;

    if (!finalAssignee && category) {
      const routingUsers = await prisma.user.findMany({
        where: {
          organizationId: organizationId,
          autoAssignCategories: { has: category },
        },
        include: { teams: true },
      });

      if (routingUsers.length > 0) {
        const localUsers = routingUsers.filter((u) => u.siteLocation === resolvedLocationName);
        const centralUsers = routingUsers.filter(
          (u) =>
            u.siteLocation?.toLowerCase().includes("shop") ||
            u.siteLocation?.toLowerCase().includes("warehouse"),
        );

        const allAssignedUsersMap = new Map();
        [...localUsers, ...centralUsers].forEach((u) => allAssignedUsersMap.set(u.id, u));
        const uniqueAssignedUsers = Array.from(allAssignedUsersMap.values());

        if (uniqueAssignedUsers.length > 0) {
          const primaryUser = uniqueAssignedUsers[0];
          finalAssignee = primaryUser.id;

          if (!finalTeam && primaryUser.teams && primaryUser.teams.length > 0) {
            finalTeam = primaryUser.teams[0].id;
          }

          if (uniqueAssignedUsers.length > 1) {
            finalAdditionalEmails = uniqueAssignedUsers
              .slice(1)
              .map((u: any) => u.email)
              .join(",");
          }
        }
      }
    }

    const newWorkOrder = await prisma.workOrder.create({
      data: {
        title,
        description,
        category: category && category !== "None" ? category : null,
        priority: priority || "MEDIUM",
        status: "OPEN",
        organizationId,
        createdBy: createdBy || null,
        assignedTo: finalAssignee,
        additionalAssigneeEmails: finalAdditionalEmails,
        teamId: finalTeam,
        assetId: assetId || null,
        locationName: resolvedLocationName,
        parentWorkOrderId: parentWorkOrderId ? parseInt(parentWorkOrderId) : null,
        dueDate: dueDate ? new Date(dueDate) : null,
        estimatedHours: parsedHours,
      },
      include: { creator: true, assignee: true },
    });

    await redis.del(`workorders:${organizationId}`).catch(() => {});

    if (newWorkOrder.assignedTo) {
      await notifyUser(
        newWorkOrder.assignedTo,
        "New Work Order Assigned",
        `You have been assigned to a new work order: ${newWorkOrder.title}`,
        "WORK_ORDER_ASSIGNED",
        String(newWorkOrder.id),
      );
    }
    
    if (finalAdditionalEmails) {
      const emailList = finalAdditionalEmails.split(",").map(e => e.trim());
      const additionalUsers = await prisma.user.findMany({
        where: { email: { in: emailList } }
      });
      
      for (const u of additionalUsers) {
        await notifyUser(
          u.id,
          "New Work Order Assigned",
          `You have been assigned to a new work order: ${newWorkOrder.title}`,
          "WORK_ORDER_ASSIGNED",
          String(newWorkOrder.id),
        );
      }
    }

    try {
      let emailsToSend: string[] = [];
      
      if (newWorkOrder.assignee?.email) {
        emailsToSend.push(newWorkOrder.assignee.email);
      }
      
      if (finalAdditionalEmails) {
        const extraEmails = finalAdditionalEmails.split(",").map(e => e.trim());
        emailsToSend = [...emailsToSend, ...extraEmails];
      }
      
      if (emailsToSend.length > 0) {
        const mailOptions = {
          from: `"Pulseworks CMMS" <${process.env.EMAIL_USER}>`,
          to: emailsToSend,
          subject: `New Assignment: WO-${newWorkOrder.id} - ${newWorkOrder.title}`,
          html: `
            <h3>You have been assigned to a new Work Order</h3>
            <p><strong>Ticket:</strong> WO-${newWorkOrder.id}</p>
            <p><strong>Title:</strong> ${newWorkOrder.title}</p>
            <p><strong>Priority:</strong> ${newWorkOrder.priority}</p>
            <p><strong>Location:</strong> ${newWorkOrder.locationName || 'Unspecified'}</p>
            <hr />
            <p>Please log in to the <a href="https://pulseworkscmms.vercel.app/#/workspace/workorder/${newWorkOrder.id}">Pulseworks CMMS dashboard</a> to view the full details.</p>
          `,
        };
        await transporter.sendMail(mailOptions);
      }
    } catch (emailErr) {}

    if (createdBy) {
      await prisma.activityLog.create({
        data: {
          action: "created the work order",
          entityType: "WORK_ORDER",
          entityTitle: `WO-${newWorkOrder.id}`,
          workOrderId: newWorkOrder.id,
          actorId: createdBy,
          organizationId: newWorkOrder.organizationId,
        },
      });
    }

    res.status(201).json(newWorkOrder);
  } catch (error) {
    logger.error(
      `[WorkOrders] CREATION ERROR: ${(error as Error).message || error}. Payload: ${JSON.stringify(req.body)}`,
    );
    res.status(500).json({ error: "Failed to create work order" });
  }
});

// 5. Update Work Order
router.put("/:id", async (req, res) => {
  const { id } = req.params;
  const numericId = parseInt(id);
  const { actorId, actionLog, ...updateData } = req.body;

  try {
    if (updateData.dueDate) updateData.dueDate = new Date(updateData.dueDate);

    const existingWO = await prisma.workOrder.findUnique({ where: { id: numericId }});
    if (!existingWO) return res.status(404).json({error: "Not Found"});

    const updatedWorkOrder = await prisma.workOrder.update({
      where: { id: numericId },
      data: updateData,
    });

    await redis.del(`workorder:single:${id}`).catch(() => {});
    await redis.del(`workorders:${updatedWorkOrder.organizationId}`).catch(() => {});

    // LOG ACTIVITY TO UNIVERSAL STREAM
    if (actorId && actionLog) {
      await prisma.activityLog.create({
        data: {
          action: actionLog,
          entityType: "WORK_ORDER",
          entityTitle: `WO-${numericId}`,
          workOrderId: numericId,
          actorId: actorId,
          organizationId: updatedWorkOrder.organizationId,
        },
      });
    }

    if (
      (updateData.status === "COMPLETED" ||
        updateData.status === "CLOSED" ||
        updateData.status === "COMPLETE") &&
      updatedWorkOrder.pmId
    ) {
      const pm: any = await prisma.preventiveMaintenance.findUnique({
        where: { id: updatedWorkOrder.pmId },
      });

      if (pm) {
        const nextDate = new Date(pm.nextDueDate);
        if (pm.scheduleType === "DAILY") nextDate.setDate(nextDate.getDate() + 1);
        if (pm.scheduleType === "WEEKLY") nextDate.setDate(nextDate.getDate() + 7);
        if (pm.scheduleType === "MONTHLY") nextDate.setMonth(nextDate.getMonth() + 1);
        if (pm.scheduleType === "QUARTERLY") nextDate.setMonth(nextDate.getMonth() + 3);
        if (pm.scheduleType === "YEARLY") nextDate.setFullYear(nextDate.getFullYear() + 1);

        await prisma.preventiveMaintenance.update({
          where: { id: pm.id },
          data: { nextDueDate: nextDate },
        });

        await prisma.workOrder.create({
          data: {
            title: `[PM] ${pm.title}`,
            description: pm.description,
            priority: "MEDIUM",
            status: "OPEN",
            dueDate: nextDate,
            organizationId: pm.organizationId,
            assignedTo: pm.assigneeId || null,
            teamId: pm.teamId || null,
            assetId: pm.assetId || null,
            createdBy: updatedWorkOrder.createdBy,
            pmId: pm.id,
            taskData: pm.taskData || [],
            partsNames:
              pm.partsData && pm.partsData.length > 0
                ? pm.partsData.map((p: any) => p.name).join(", ")
                : null,
          },
        });
      }
    }

    if (updateData.status && updatedWorkOrder.createdBy) {
      await notifyUser(
        updatedWorkOrder.createdBy,
        "Work Order Status Updated",
        `Work order #${updatedWorkOrder.id} is now ${updateData.status}.`,
        "WORK_ORDER_UPDATED",
        String(updatedWorkOrder.id),
      );
    }

    res.status(200).json(updatedWorkOrder);
  } catch (error) {
    logger.error(`[WorkOrders] Update WO Error: ${(error as Error).message || error}`);
    res.status(500).json({ error: "Failed to update work order" });
  }
});

// 6. Delete Work Order
router.delete("/:id", async (req, res) => {
  try {
    const numericId = parseInt(req.params.id);
    if (isNaN(numericId)) return res.status(400).json({ error: "Invalid ID format" });

    const existingWO = await prisma.workOrder.findUnique({ where: { id: numericId } });

    await prisma.workOrder.delete({
      where: { id: numericId },
    });

    if (existingWO) {
      await redis.del(`workorder:single:${numericId}`).catch(() => {});
      await redis.del(`workorders:${existingWO.organizationId}`).catch(() => {});
    }

    res.status(204).send();
  } catch (error) {
    logger.error(`[WorkOrders] Delete Error: ${(error as Error).message || error}`);
    res.status(500).json({ error: "Failed to delete work order" });
  }
});

// 7. Post a Comment & HANDLE MENTIONS
router.post("/:id/comments", async (req, res) => {
  const { text, authorId } = req.body;
  const numericId = parseInt(req.params.id);
  
  try {
    const wo = await prisma.workOrder.findUnique({ 
      where: { id: numericId }, 
      select: { organizationId: true, title: true }
    });
    if (!wo) return res.status(404).json({error: "Work order not found"});

    const comment = await prisma.comment.create({
      data: { text, authorId, workOrderId: numericId },
      include: { author: true },
    });
    
    // Log comment event in universal activity stream
    await prisma.activityLog.create({
      data: {
        action: `added a comment: "${text.substring(0, 50)}${text.length > 50 ? '...' : ''}"`,
        entityType: "WORK_ORDER",
        entityTitle: `WO-${numericId}`,
        workOrderId: numericId,
        actorId: authorId,
        organizationId: wo.organizationId,
      }
    });

    await redis.del(`workorder:single:${numericId}`).catch(() => {});

    // MENTION PARSING & NOTIFICATIONS
    const mentionRegex = /@([a-zA-Z0-9]+(?:\s+[a-zA-Z0-9]+)?)/g;
    const mentions = [...text.matchAll(mentionRegex)].map(m => m[1].trim().toLowerCase());

    if (mentions.length > 0) {
      const allUsers = await prisma.user.findMany({
        where: { organizationId: wo.organizationId }
      });
      
      const taggedUsers = allUsers.filter(u => {
        const full = `${u.firstName} ${u.lastName}`.toLowerCase();
        const first = u.firstName.toLowerCase();
        return mentions.includes(full) || mentions.includes(first);
      });

      for (const taggedUser of taggedUsers) {
        // Send In-App Notification
        await notifyUser(
          taggedUser.id,
          "You were mentioned",
          `${comment.author.firstName} mentioned you in WO-${numericId}`,
          "MENTION",
          String(numericId)
        );

        // Send Email Alert
        if (taggedUser.email) {
          try {
             await transporter.sendMail({
              from: `"Pulseworks CMMS" <${process.env.EMAIL_USER}>`,
              to: taggedUser.email,
              subject: `You were mentioned in WO-${numericId}`,
              html: `
                <h3>${comment.author.firstName} mentioned you in a comment</h3>
                <p><strong>WO-${numericId}:</strong> ${wo.title}</p>
                <blockquote style="border-left: 4px solid #ccc; padding-left: 10px; color: #555;">
                  ${text}
                </blockquote>
                <p><a href="https://pulseworkscmms.vercel.app/#/workspace/workorder/${numericId}">Click here to view the ticket</a></p>
              `,
            });
          } catch(e) {
            logger.error(`Mention email dispatch failed: ${e}`);
          }
        }
      }
    }

    res.status(201).json(comment);
  } catch (error) {
    logger.error(`[WorkOrders] Add Comment Error: ${(error as Error).message || error}`);
    res.status(500).json({ error: "Failed to add comment" });
  }
});

// 8. Update a Comment
router.put("/:id/comments/:commentId", async (req, res) => {
  try {
    const { text } = req.body;
    const comment = await prisma.comment.update({
      where: { id: req.params.commentId },
      data: { text },
    });

    await redis.del(`workorder:single:${req.params.id}`).catch(() => {});

    res.json(comment);
  } catch (error) {
    logger.error(`[WorkOrders] Update Comment Error: ${(error as Error).message || error}`);
    res.status(500).json({ error: "Failed to update comment" });
  }
});

// 9. Delete a Comment
router.delete("/:id/comments/:commentId", async (req, res) => {
  try {
    await prisma.comment.delete({
      where: { id: req.params.commentId },
    });

    await redis.del(`workorder:single:${req.params.id}`).catch(() => {});

    res.status(204).send();
  } catch (error) {
    logger.error(`[WorkOrders] Delete Comment Error: ${(error as Error).message || error}`);
    res.status(500).json({ error: "Failed to delete comment" });
  }
});

export default router;